language: node_js
node_js:
  - "4.2"

cache:
  directories:
    - node_modules
    - bower_components

install:
	- npm install -g grunt-cli
	- npm install -g bower
	- npm install -g karma-cli
	- npm install
	- bower install  